# GitHub Actions Workflow for ServiceNow Deployment
# This workflow automates the deployment of ServiceNow components to different environments

name: ServiceNow CI/CD

on:
  push:
    # branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  lint:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install ESLint
        run: npm install eslint
        
      - name: Run ESLint
        run: npx eslint "src/**/*.js" --max-warnings=0
  
  validate:
    name: Validate ServiceNow Files
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install ServiceNow CLI
        run: npm install -g @servicenow/cli
        
      - name: Validate Files
        run: |
          echo "Validating ServiceNow files structure..."
          # Add commands to validate ServiceNow files
  
  deploy:
    name: Deploy to ServiceNow
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod' || 'dev') }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install ServiceNow CLI
        run: npm install -g @servicenow/cli
        
      - name: Create Update Set
        run: |
          echo "Creating update set from source files..."
          # Add commands to create update set
        
      - name: Deploy to ServiceNow
        run: |
          echo "Deploying to ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod' || 'dev') }} environment..."
          # Add commands to deploy to ServiceNow
        env:
          SN_INSTANCE: ${{ secrets.SN_INSTANCE }}
          SN_USERNAME: ${{ secrets.SN_USERNAME }}
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
